//
//  ImageRequest.cs
//
//  Author:
//       Manjeet <msudhanshu@kiwiup.com>
//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public struct ImageRequest
{
	public string ImageUrl;
	public string ImageName;
	public int width;
	public int height;
	public ImageDownloadType imageType;

	public ImageRequest(string _ImageName, string _ImageUrl, ImageDownloadType _imageType) {
		this.ImageName = _ImageName;
		this.ImageUrl = _ImageUrl;
		this.imageType = _imageType;
		width = 512;
		height = 512;
	}

	public ImageRequest(string _ImageUrl, ImageDownloadType _imageType) {
		this.ImageName = "Guess??";
		this.ImageUrl = _ImageUrl;
		this.imageType = _imageType;
		width = 512;
		height = 512;
	}
}

public enum ImageDownloadType {
	FACEBOOKAPI,
	RESOURCE,
	URL
}


